### ISSUE TITLE
Need an icon to represent "Danger"

### ISSUE THREAD

**Issue by sbiswas2** [sbiswas2/call-for-code#9]
this will represent a warning when using the app

**Comment by jmdunne** [comment]
![Screen Shot 2021-08-18 at 3 03 26 PM](https://user-images.githubusercontent.com/68917447/130981763-94d31949-f0f1-4c84-86ab-7791f4c1a599.png)

Here is the danger icon for the <div> we discussed

**Comment by sbiswas2** [comment]
this looks great!
